spring:
    datasource:
        url: jdbc:mariadb://tardydb.cprkwuh7mclf.ap-northeast-2.rds.amazonaws.com/tardydb
        driverClassName: org.mariadb.jdbc.Driver
        username: tardydb
        password: tardygramdb
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        # show-sql: true
        # properties:
        #    hibernate:
        #        format_sql: true
server:
    port: 9000
